site_name: 'python-app8'
site_description: 'Main documentation for the python-app8'
repo_url: https://github.com/DaggupatiPavan-1/python-app8
edit_uri: edit/main/docs

plugins:
  - techdocs-core

# For sidebar navigation on https://backstage.io/, see `microsite/sidebars.json`
nav:
  - Overview:
      - Getting started: 'docs/index.md'
